name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: aws
    steps:
      - name: Test AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws s3 ls
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        run: npm i -g @architect/architect aws-sdk
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune
        env:
          ARC_AWS_CREDS: ecs
