name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev
            url: dev.gcn.nasa.gov
          - env: test
            url: test.gcn.nasa.gov
          - env: prod
            url: gcn.nasa.gov
    concurrency: ${{ matrix.env }}
    runs-on:
      - aws
      - ${{ matrix.env }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ matrix.url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        run: npm i -g 'git+https://github.com/lpsinger/architect.git#caret-versions' 'git+https://github.com/lpsinger/hydrate.git#hydrate-preserve-overrides' aws-sdk
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune --production
