name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: aws
    steps:
      - name: Install AWS credentials
        run: |
          curl -o cred.json 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
          mkdir -p ~/.aws
          echo [default] > ~/.aws/credentials
          aws_access_key_id=$(jq .AccessKeyId cred.json) >> ~/.aws/credentials
          aws_secret_access_key=$(jq .SecretAccessKey cred.json) >> ~/.aws/credentials
          aws_session_token=$(jq .Token cred.json) >> ~/.aws/credentials
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        run: npm i -g @architect/architect aws-sdk
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune
        env:
          AWS_PROFILE: default
          AWS_REGION: us-east-1
