name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: aws
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        run: npm i -g @architect/architect@^10.0.0-RC.0 aws-sdk
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune
