name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: aws
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        # FIXME: remove explicit @architect/package@^8.0.0 @architect/deploy@^4.0.1
        # dependencies once architect 10 is released
        run: npm i -g @architect/architect aws-sdk @architect/package@^8.0.0 @architect/deploy@^4.0.1
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune
