name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run eslint linter
        run: npx eslint --max-warnings 0 .
      - name: Run TypeScript compiler
        run: npx tsc -p .
      - name: Run Prettier code style checks
        run: npx prettier -c .
